### ISSUE TITLE
Comments on SFA 7/7/2020

### ISSUE THREAD

**Issue by hannahjames77** [mcwimm/SFA#1]
-Include in instructions that data/ csv file needs to be in project folder
-To load new data file directly after another, I found that program needs to be started over, otherwise K values from the previous data set are not cleared
-Saving graphics to folder= mixed success

**Comment by mcwimm** [comment]
**data/ csv file**
What do you mean by "data/ csv file"? Is it the data you'd like to analyse? If yes, they can be anywhere because you can browse to the desired directory (at least that's how it works for me). 
Can you please specify on which system (linux, windows, ...) you use the app ?
And can you provide an example where the upload doesn't work.

**Comment by mcwimm** [comment]
**upload a new file**
I have also noticed this problem. Do you think it would be helpful if there is a "delete-k-values"-button?

**Comment by mcwimm** [comment]
**Saving graphics**
Can you please provide examples.

**Comment by hannahjames77** [comment]
In the Sap flow rate calculation section, a graph only appears when all 3 methods are selected: 
![image](https://user-images.githubusercontent.com/62958704/87805790-88062e00-c81b-11ea-8568-c6203970f1f4.png)
